export const GIT_REPO_REQUEST = 'GIT_REPO_REQUEST';
export const GIT_REPO_SUCCESS = 'GIT_REPO_SUCCESS';
export const GIT_REPO_FAILURE = 'GIT_REPO_FAILURE';

export const GIT_FOLLOWERS_REQUEST = 'GIT_FOLLOWERS_REQUEST';
export const GIT_FOLLOWERS_SUCCESS = 'GIT_FOLLOWERS_SUCCESS';
export const GIT_FOLLOWERS_FAILURE = 'GIT_FOLLOWERS_FAILURE';
